name: CI - US
on:
  workflow_call:

jobs:
  build_test:
    runs-on: ubuntu-latest
    env:
      TENANT: us
      APP_ENV: local
    steps:
      - uses: actions/checkout@v4
      - run: echo "TENANT=$TENANT BRANCH=$GITHUB_REF_NAME SHA=$GITHUB_SHA"
