name: CI - env demo
on: [push]

jobs:
  env:
    runs-on: ubuntu-latest
    env:
      APP_ENV: local
      TENANT: intl
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "APP_ENV=$APP_ENV"