name: CI - env demo
on:
  push:
    branches:
      - main
      - "INTL/**"
      - "US/**"
      - "feature/**"

jobs:
  env:
    runs-on: ubuntu-latest
    env:
      APP_ENV: local
      TENANT: intl
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "APP_ENV=$APP_ENV"
          echo "TENANT=$TENANT"
          echo "BRANCH=${GITHUB_REF_NAME}"
          echo "SHA=${GITHUB_SHA}"
