name: CI - multi tenant
on:
  push:
    branches: [ main, "INTL/**", "US/**" ]
  pull_request:
    branches: [ main ]

jobs:
  intl:
    if: startsWith(github.ref_name, 'INTL/')
    uses: ./.github/workflows/ci.intl.yml

  us:
    if: startsWith(github.ref_name, 'US/') || github.ref_name == 'main'
    uses: ./.github/workflows/ci.us.yml
